[A7-MultiKits]

# Each multiclass kit definition starts with an index (>= 1)
# class: Symbolic label (CLASS.IDS) or numeric class id; only multiclass definitions are allowed
#1_class=FIGHTER_THIEF
# kit1/kit2/kit3: Up to 3 kits for the individual class aspects (only one kit per class aspect allowed).
#1_kit1=KENSAI
#1_kit2=SWASHBUCKLER
# Optional display title of the multiclass kit:
#  - Omit or leave empty to autogenerate title.
#1_title=Sword Saint
# Optional internal mc kit name:
#  - Should only consist of ascii letters, digits, or underscores.
#  - Must not be longer than 32 characters.
#  - Capital letters are recommended but not required.
#  - Omit or leave empty to autogenerate.
#1_name=A7_SWORD_SAINT


[Metadata]

# Full name of the mod, without version number
Name = Multiclass Kits

# Author name or nick, don't use email address
Author = Argent77

# Short description of the mod, main goals, features etc
Description = A mod for BG:EE, SoD, BG2:EE, EET, and IWD:EE that allows you to install true multiclass kits from any combination of single-class kits.

# Web address of mod readme file (filename is case-sensitive!) You can link to txt, md, html, pdf etc.
Readme = https://raw.githubusercontent.com/Argent77/A7-MultiKits/master/A7-MultiKits/doc/readme.txt

# Web address of mod dedicated forum or forum thread
Forum = https://www.gibberlings3.net/forums/topic/40601-mod-multiclass-kits

# Web address of mod personal Homepage, no need to duplicate with a mod dedicated forum
# Homepage = https://www.example.com

# if you use Github.com, simply use https://github.com/AccountOrOrgName/RepositoryName
# read more about Delta Updates https://github.com/ALIENQuake/ProjectInfinity/wiki/Delta-Updates-for-mods-hosted-at-Github
Download = https://github.com/Argent77/A7-MultiKits

# Type of LABELs used by the mod, read more here https://www.gibberlings3.net/forums/topic/32516-tutorial-what-is-label
LabelType = GloballyUnique

# This mod should be installed *before* the mods listed after the keyword
Before = dw_talents

# This mod should be installed *after* the mods listed after the keyword
After = EET
