INCLUDE ~%MOD_FOLDER%/lib/custom_class_interactive.tph~

// Function Overview:
// a7#list_multikits                  Diagnostic function that lists available kit combinations for the specified multiclass.
// a7#install_multikits               Installs all available kit combinations for the specified multiclass.
// a7#install_multikits_interactive   Installs kit combinations for the specified multiclass based on user input.
// a7#resolve_string                  Performs variable replacements in the given string.


/** Diagnostic function that lists available kit combinations for the specified multiclass. */
DEFINE_ACTION_FUNCTION a7#list_multikits
INT_VAR
  class = 0
BEGIN
  OUTER_PATCH ~~ BEGIN LOOKUP_IDS_SYMBOL_OF_INT class_label ~class~ class END
  ACTION_MATCH class WITH
    7 8 9 10 13 14 15 16 17 18 BEGIN  // all available multi-classes
      ACTION_DEFINE_ARRAY class_whitelist BEGIN ~%class_label%~ END
      LAF a7#collect_class_info
        INT_VAR
          allow_kits = 1
          allow_multi = 1
          allow_multi_kits = 1
          allow_custom_multi_kits = 1
          include_trueclass = 0
        STR_VAR
          class_whitelist_name = ~class_whitelist~
        RET
          class_map
        RET_ARRAY
          class_map
      END

      PRINT ~Classes found: %class_map%~
      OUTER_FOR (cls_idx = 0; cls_idx < class_map; ++cls_idx) BEGIN
        OUTER_SPRINT class_label $class_map(~%cls_idx%~ ~symbol~)
        OUTER_SPRINT class_title $class_map(~%cls_idx%~ ~title~)
        PRINT ~Class #%cls_idx%: label=%class_label%, title=%class_title%~
        OUTER_SET num_kits = $class_map(~%cls_idx%~ ~kit~)
        PRINT ~Kits found: %num_kits%~
        OUTER_FOR (kit_idx = 0; kit_idx < num_kits; ++kit_idx) BEGIN
          OUTER_SET kit_id = $class_map(~%cls_idx%~ ~kit~ ~%kit_idx%~)
          ACTION_IF (kit_id == "-1") BEGIN
            OUTER_SPRINT kit_label $class_map(~%cls_idx%~ ~kit~ ~%kit_idx%~ ~symbol~)
            OUTER_SPRINT kit_title $class_map(~%cls_idx%~ ~kit~ ~%kit_idx%~ ~title~)
            OUTER_SET kit_id1 = $class_map(~%cls_idx%~ ~kit~ ~%kit_idx%~ ~kit1~)
            OUTER_SET kit_id2 = $class_map(~%cls_idx%~ ~kit~ ~%kit_idx%~ ~kit2~)
            OUTER_SET kit_id3 = $class_map(~%cls_idx%~ ~kit~ ~%kit_idx%~ ~kit3~)
            PRINT ~Kit #%kit_idx%: label=%kit_label%, title=%kit_title%, kit1=%kit_id1%, kit2=%kit_id2%, kit3=%kit_id3%~
          END ELSE BEGIN
            PRINT ~Skipping trueclass kit...~
          END
        END
      END
    END
    DEFAULT
      OUTER_SPRINT string @3006 // Class is not supported: <class_label>
      LAF a7#resolve_string STR_VAR string RET msg = string END
      FAIL ~%msg%~
  END
END


/**
 * Installs all available kit combinations for the specified multiclass.
 *
 * INT_VAR class    Numeric multiclass identifier (CLASS.IDS).
 */
DEFINE_ACTION_FUNCTION a7#install_multikits
INT_VAR
  class = 0
BEGIN
  OUTER_PATCH ~~ BEGIN LOOKUP_IDS_SYMBOL_OF_INT class_label ~class~ class END
  ACTION_MATCH class WITH
    7 8 9 10 13 14 15 16 17 18 BEGIN  // all available multi-classes
      PRINT @2002 // Gathering kit information. This may take a while...
      ACTION_DEFINE_ARRAY class_whitelist BEGIN ~%class_label%~ END
      LAF a7#collect_class_info
        INT_VAR
          allow_kits = 1
          allow_multi = 1
          allow_multi_kits = 1
          allow_custom_multi_kits = 1
          include_trueclass = 0
        STR_VAR
          class_whitelist_name = ~class_whitelist~
        RET
          class_map
        RET_ARRAY
          class_map
      END

      ACTION_IF (class_map == 1) BEGIN
        OUTER_SET num_kits = $class_map(~0~ ~kit~)
        OUTER_SPRINT class_title $class_map(~0~ ~title~)
        ACTION_IF (num_kits > 0) BEGIN
          ACTION_IF (NOT IS_SILENT) BEGIN
            OUTER_SPRINT string @3000 // Installing <num_kits> kits for class <class_title>...
            LAF a7#resolve_string STR_VAR string RET msg = string END
            PRINT ~%msg%~
          END

          OUTER_SET kit_count = 0
          OUTER_FOR (kit_idx = 0; kit_idx < num_kits; ++kit_idx) BEGIN
            OUTER_SET kit = $class_map(~0~ ~kit~ ~%kit_idx%~)
            ACTION_IF (kit == "-1") BEGIN
              // creating multiclass kit
              OUTER_SPRINT kit_name $class_map(~0~ ~kit~ ~%kit_idx%~ ~symbol~)
              OUTER_SPRINT kit_title $class_map(~0~ ~kit~ ~%kit_idx%~ ~title~)
              OUTER_SET mixed = RESOLVE_STR_REF(~%kit_title%~)
              OUTER_SET kit1 = $class_map(~0~ ~kit~ ~%kit_idx%~ ~kit1~)
              OUTER_SET kit2 = $class_map(~0~ ~kit~ ~%kit_idx%~ ~kit2~)
              OUTER_SET kit3 = $class_map(~0~ ~kit~ ~%kit_idx%~ ~kit3~)
              LAF a7#create_multikit
                INT_VAR
                  class kit1 kit2 kit3 mixed
                  visible = 1
                  suppress_warnings = 1 // needed for some class/kit combinations because of non-standard CLAB resrefs
                STR_VAR
                  kit_name
                RET
                  kit_id
              END

              ACTION_IF (kit_id != "-1") BEGIN
                OUTER_SET kit_count += 1
                ACTION_IF (NOT IS_SILENT) BEGIN
                  OUTER_SPRINT string @3001 // Kit installed successfully: <kit_title>
                  LAF a7#resolve_string STR_VAR string RET msg = string END
                  PRINT ~%msg%~
                END
              END ELSE BEGIN
                OUTER_SPRINT string @3002 // WARNING: Could not install kit: <kit_title>
                LAF a7#resolve_string STR_VAR string RET msg = string END
                WARN ~%msg%~
              END
            END
          END
          OUTER_SPRINT string @3003 // Successfully installed <kit_count> kits for class <class_title>.
          LAF a7#resolve_string STR_VAR string RET msg = string END
          PRINT ~%msg%~
        END ELSE BEGIN
          OUTER_SPRINT string @3004 // No kits available for class <class_title>.
          LAF a7#resolve_string STR_VAR string RET msg = string END
          ABORT ~%msg%~
        END
      END ELSE BEGIN
        WARN @3005  // WARNING: No kits available for the specified multiclass.
      END
    END
    DEFAULT
      OUTER_SPRINT string @3006 // Class is not supported: <class_label>
      LAF a7#resolve_string STR_VAR string RET msg = string END
      FAIL ~%msg%~
  END
END


/**
 * Installs kit combinations for the specified multiclass based on user input.
 *
 * INT_VAR class                Numeric multiclass identifier (CLASS.IDS).
 * INT_VAR choose_custom_title  Specifies whether the operation should ask the user for a custom title if a non-existing
 *                              multiclass kit has been selected. (Default: 1)
 */
DEFINE_ACTION_FUNCTION a7#install_multikits_interactive
INT_VAR
  class = 0
  choose_custom_title = 1
BEGIN
  OUTER_PATCH ~~ BEGIN LOOKUP_IDS_SYMBOL_OF_INT class_label ~class~ class END
  ACTION_MATCH class WITH
    7 8 9 10 13 14 15 16 17 18 BEGIN  // all available multi-classes
      LAF a7#interactive_kit_selection
        INT_VAR class choose_custom_title
        RET success
        RET_ARRAY class_map_selected
      END

      ACTION_IF (success == 1) BEGIN
        // perform kit installation
        OUTER_SPRINT class_title $class_map_selected(~0~ ~title~)
        OUTER_SET num_kits = $class_map_selected(~0~ ~kit~)
        ACTION_IF (NOT IS_SILENT) BEGIN
          OUTER_SPRINT string @3000 // Installing <num_kits> kits for class <class_title>...
          LAF a7#resolve_string STR_VAR string RET msg = string END
          PRINT ~%msg%~
        END

        OUTER_SET kit_count = 0
        OUTER_FOR (kit_idx = 0; kit_idx < num_kits; ++kit_idx) BEGIN
          // creating multiclass kit
          OUTER_SPRINT kit_name $class_map_selected(~0~ ~kit~ ~%kit_idx%~ ~symbol~)
          OUTER_SPRINT kit_title $class_map_selected(~0~ ~kit~ ~%kit_idx%~ ~title~)
          OUTER_SET mixed = RESOLVE_STR_REF(~%kit_title%~)
          OUTER_SET kit1 = $class_map_selected(~0~ ~kit~ ~%kit_idx%~ ~kit1~)
          OUTER_SET kit2 = $class_map_selected(~0~ ~kit~ ~%kit_idx%~ ~kit2~)
          OUTER_SET kit3 = $class_map_selected(~0~ ~kit~ ~%kit_idx%~ ~kit3~)
          LAF a7#create_multikit
            INT_VAR
              class kit1 kit2 kit3 mixed
              visible = 1
              suppress_warnings = 1 // needed for some class/kit combinations because of non-standard CLAB resrefs
            STR_VAR
              kit_name
            RET
              kit_id
          END

          ACTION_IF (kit_id != "-1") BEGIN
            OUTER_SET kit_count += 1
            ACTION_IF (NOT IS_SILENT) BEGIN
              OUTER_SPRINT string @3001 // Kit installed successfully: <kit_title>
              LAF a7#resolve_string STR_VAR string RET msg = string END
              PRINT ~%msg%~
            END
          END ELSE BEGIN
            OUTER_SPRINT string @3002 // WARNING: Could not install kit: <kit_title>
            LAF a7#resolve_string STR_VAR string RET msg = string END
            WARN ~%msg%~
          END
        END

        ACTION_IF (kit_count > 0) BEGIN
          OUTER_SPRINT string @3003 // Successfully installed <kit_count> kits for class <class_title>.
          LAF a7#resolve_string STR_VAR string RET msg = string END
          PRINT ~%msg%~
        END ELSE BEGIN
          OUTER_SPRINT string @3004 // No kits available for class <class_title>.
          LAF a7#resolve_string STR_VAR string RET msg = string END
          ABORT ~%msg%~
        END
      END ELSE ACTION_IF (success == "-1") BEGIN
        // installation aborted
        ABORT @3007 // Kit installation aborted.
      END ELSE BEGIN
        FAIL ~Kit installation failed.~
      END
    END
    DEFAULT
      OUTER_SPRINT string @3006 // Class is not supported: <class_label>
      LAF a7#resolve_string STR_VAR string RET msg = string END
      FAIL ~%msg%~
  END
END


/**
 * Installs user-defined multiclass kits.
 *
 * STR_VAR ini_file       Path of the INI file with mc kit definitions.
 * STR_VAR section_name   Name of the ini section with kit definitions. (Default: A7-MultiKits)
 * RET num_installed      Returns the number of successfully installed kits
 */
DEFINE_ACTION_FUNCTION a7#install_custom_multikits
STR_VAR
  ini_file = ~~
  section_name = ~A7-MultiKits~
RET
  num_installed
BEGIN
  OUTER_SET num_installed = 0
  ACTION_IF (NOT ~%ini_file%~ STR_EQ ~~ && FILE_EXISTS ~%ini_file%~) BEGIN
    COPY ~%ini_file%~ ~override~
      SET start_ofs = 0
      SET end_ofs = BUFFER_LENGTH
      PATCH_IF (NOT ~%section_name%~ STR_EQ ~~) BEGIN
        SET p1 = INDEX_BUFFER(~^[ %TAB%]*\[%section_name%\]~ start_ofs)
        PATCH_IF (p1 >= 0) BEGIN
          SET start_ofs = p1
          SET p2 = INDEX_BUFFER(~^[ %TAB%]*\[.+\]~ p1 + 1)
          PATCH_IF (p2 > p1) BEGIN
            SET end_ofs = p2
          END
        END
      END
      READ_ASCII start_ofs ini_buffer (end_ofs - start_ofs)
    BUT_ONLY

    OUTER_PATCH ~%ini_buffer%~ BEGIN
      // open-ended kit parsing
      FOR (kit_index = 1; kit_index > 0; ++kit_index) BEGIN
        PATCH_IF (INDEX_BUFFER(~^[ %TAB%]*%kit_index%_class[ %TAB%]*=~) >= 0) BEGIN
          SPRINT string @3100 // Installing kit #<kit_index>...~
          LPF a7#resolve_string STR_VAR string RET msg = string END
          PATCH_PRINT ~%msg%~

          // getting class
          LPF a7#get_ini_entry STR_VAR key = EVAL ~%kit_index%_class~ def_value = ~~ RET mc_class = value END
          SET success = NOT ~%mc_class%~ STR_EQ ~~
          PATCH_IF (success) BEGIN
            SET class = IS_AN_INT ~mc_class~ ? mc_class : IDS_OF_SYMBOL(~class~ ~%mc_class%~)
            LPF a7#validate_multiclass INT_VAR class RET success class1 class2 class3 END
          END
          PATCH_IF (NOT success) BEGIN
            SPRINT string @3101  // WARNING: Not a valid combination class: <mc_class>
            LPF a7#resolve_string STR_VAR string RET msg = string END
            PATCH_WARN ~%msg%~
          END

          PATCH_IF (success) BEGIN
            // getting kits
            SET kit1 = "-1"
            SET kit2 = "-1"
            SET kit3 = "-1"
            FOR (i = 1 j = 1; success && i <= 3; ++i) BEGIN
              LPF a7#get_ini_entry STR_VAR key = EVAL ~%kit_index%_kit%i%~ def_value = ~~ RET kit = value END
              PATCH_IF (NOT ~%kit%~ STR_EQ ~~) BEGIN
                SET kit_id = IS_AN_INT ~kit~ ? kit : IDS_OF_SYMBOL(~kit~ ~%kit%~)
                PATCH_IF (kit_id != "-1") BEGIN
                  LPF a7#get_kit_class INT_VAR kit = kit_id RET kit_class END
                  PATCH_IF (kit_class == class1 || kit_class == class2 || kit_class == class3) BEGIN
                    SET EVAL ~kit%j%~ = kit_id
                    SET j += 1
                  END ELSE BEGIN
                    SET success = 0
                    SPRINT string @3102 // WARNING: Kit does not belong to any of the parent classes: <kit>
                    LPF a7#resolve_string STR_VAR string RET msg = string END
                    PATCH_WARN ~%msg%~
                  END
                END ELSE BEGIN
                  SET success = 0
                  SPRINT string @3106 // WARNING: Not a valid source kit: <kit>
                  LPF a7#resolve_string STR_VAR string RET msg = string END
                  PATCH_WARN ~%msg%~
                END
              END
            END
          END

          PATCH_IF (success) BEGIN
            // getting kit title
            LPF a7#get_ini_entry STR_VAR key = EVAL ~%kit_index%_title~ def_value = ~~ RET value END
            PATCH_IF (NOT ~%value%~ STR_EQ ~~) BEGIN
              SET mixed = RESOLVE_STR_REF(~%value%~)
            END ELSE BEGIN
              SET mixed = "-1"
            END

            // getting symbolic kit name
            LPF a7#get_ini_entry STR_VAR key = EVAL ~%kit_index%_name~ def_value = ~~ RET kit_name = value END
            PATCH_IF (NOT ~%kit_name%~ STR_EQ ~~ && (STRING_LENGTH ~%kit_name%~ > 32 || ~%kit_name%~ STRING_MATCHES_REGEXP ~^[0-9a-z_#!-]+$~ != 0)) BEGIN
              LPF a7#generate_kit_name INT_VAR class kit1 kit2 kit3 RET auto_kit_name = kit_name END
              SPRINT string @3103 // WARNING: Invalid kit name: <kit_name>. Using autogenerated name: <auto_kit_name>
              LPF a7#resolve_string STR_VAR string RET msg = string END
              PATCH_WARN ~%msg%~
              SPRINT kit_name ~%auto_kit_name%~
            END

            // installing kit
            INNER_ACTION BEGIN
              LAF a7#create_multikit
                INT_VAR class kit1 kit2 kit3 mixed visible = 1
                STR_VAR kit_name
                RET kit_id
              END
              ACTION_IF (kit_id != "-1") BEGIN
                OUTER_SET num_installed += 1
                OUTER_SPRINT string @3104 // Kit #<kit_index> installed successfully.
                LAF a7#resolve_string STR_VAR string RET msg = string END
                PRINT ~%msg%~
              END ELSE BEGIN
                OUTER_SPRINT string @3105  // WARNING: Kit #<kit_index> could not be installed.
                LAF a7#resolve_string STR_VAR string RET msg = string END
                WARN ~%msg%~
              END
            END
          END ELSE BEGIN
            SPRINT string @3105  // WARNING: Kit #<kit_index> could not be installed.
            LPF a7#resolve_string STR_VAR string RET msg = string END
            PATCH_WARN ~%msg%~
          END
        END ELSE BEGIN
          SET kit_index = "-1"
        END
      END
    END
  END
END


/**
 * Returns the value for the specified ini key.
 *
 * STR_VAR key        Name of the ini key.
 * STR_VAR def_value  Default value if the key does not exist.
 * RET value          Value assigned to the specified key or "def_value" if key does not exist.
 */
DEFINE_PATCH_FUNCTION a7#get_ini_entry
STR_VAR
  key = ~~
  def_value = ~~
RET
  value
BEGIN
  SPRINT value ~%def_value%~
  PATCH_IF (NOT ~%key%~ STR_EQ ~~) BEGIN
    SET match = 0
    REPLACE_EVALUATE ~^[ %TAB%]*%key%[ %TAB%]*=[ %TAB%]*\(.*\)~ BEGIN
      PATCH_IF (NOT match) BEGIN
        SPRINT value ~%MATCH1%~
        INNER_PATCH_SAVE value ~%value%~ BEGIN
          REPLACE_TEXTUALLY ~^[ %TAB%%WNL%]+~ ~~
          REPLACE_TEXTUALLY ~[ %TAB%%WNL%]+$~ ~~
        END
        SET match = 1
      END
    END ~%MATCH0%~
  END
END


/**
 * Performs variable replacements in the given string.
 * All well-formed placeholder definitions are replaced by their currently defined variable content.
 * Format: <place_holder> where "place_holder" may contain any characters of [0-9A-Za-z_].
 * Literal tokens should escape angle brackets with a backslash character.
 *
 * STR_VAR string   String with placeholders.
 * RET string       The resolved string. No change if the input string doesn't contain placeholders.
 */
DEFINE_DIMORPHIC_FUNCTION a7#resolve_string
STR_VAR
  string = ~~
RET
  string
BEGIN
  OUTER_SPRINT percent ~%~
  OUTER_PATCH_SAVE string ~%string%~ BEGIN
    REPLACE_TEXTUALLY ~\(^\|[^\\]\)<\([0-9A-Za-z_]+\)>~ ~\1%percent%\2%percent%~
    // second pass needed to catch overlapping matches
    REPLACE_TEXTUALLY ~\([^\\]\)<\([0-9A-Za-z_]+\)>~ ~\1%percent%\2%percent%~
    // normalize escaped token expressions
    REPLACE_TEXTUALLY ~\\\(<[0-9A-Za-z_]+>\)~ ~\1~
    EVAL
  END
END
